### ISSUE TITLE
Adding makefile target to build the tool only

### ISSUE THREAD

**Issue by tjyang** [hupe1980/scan4log4shell#7]
Hi @hupe1980 

I am hoping to use docker container as an isolated golang compiling  environment, not doing the  scan tests inside container.
Can you add a target to automate this goal using following example I found on internet ?
like "make docker-compile"

```
docker create -ti --name dummy IMAGE_NAME bash
docker cp dummy:/path/to/file /dest/to/file  # copy scan4log4shell out to local partition like /tmp.
docker rm -f dummy
```

**Comment by hupe1980** [comment]
You can now find Docker support in the readme
