### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Teicu** [hupe1980/scan4log4shell#9]
Hi,  

Please tell me if this tool scans only the main index or there is a option to crawl and test the entire site? I'm sorry to ask, but I haven't seen anything about this. 
Thank you

```
scan4log4shell remote url http://testphp.vulnweb.com -a
[i] Log4Shell Remote Vulnerability Scan
[i] Listening on c832bfasahsi8gnc8r20cednmxoyyyyyr.interact.sh
[i] Start scanning CIDR http://testphp.vulnweb.com
---------
[i] All request to http://testphp.vulnweb.com have been sent
[i] Completed scanning
[i] Waiting for incoming callbacks!
[i] Use ctrl+c to stop the program.
```

**Comment by Teicu** [comment]
also, is it possible to scan a text file with multiple URL addresses? i.e `scan4log4shell remote urls.txt` 

Cheers

**Comment by hupe1980** [comment]
I added the possibility to add targets over stdin. 

$ cat target.txt | ./scan4log4shell remote url

or 

$ crawler | ./scan4log4shell remote url

Unfortunately, the program does not have its own crawler

**Comment by Teicu** [comment]
Hi, 

That’s great, we can copy and paste on the target.txt file the URLs from Burp. Thank you very much. 

Cheers

**Comment by Teicu** [comment]
it seems it can't stand these commands 

```
cat targets.txt | scan4log4shell remote url 
requires at least 1 arg(s), only received 0
``` 
`cat targets.txt | scan4log4shell remote`

**Comment by hupe1980** [comment]
Are you using the correct version v1.2.0?

**Comment by Teicu** [comment]
Oh, I'm really sorry, it seems I was using the old version. my bad!

Thanks

**Comment by Teicu** [comment]
Works like a charm now! 

btw, last question, if the list of url addresses I scan is large, when the scanner finds a vulnerability does it stop or will it report them at the end when it finishes scanning?

**Comment by Teicu** [comment]
or there is the option instead of interactsh to use Burp collaborator and then we see in real time when it finds an interaction?

**Comment by hupe1980** [comment]
The scanner does not stop. All targets are always scanned.

Various catchers (TCP, DNS, LDAP) are included. Burp is not yet supported. But you can easily extend it:
https://github.com/hupe1980/scan4log4shell/blob/78167796e8b7ffdd23132ec26fdb35365172b1ec/internal/catcher.go#L18-L23
Your welcome to create a pull request
